### ISSUE TITLE
New documentation

### ISSUE THREAD

**Issue by i582** [VKCOM/noverify#1047]
- [ ] Write documentation for `baseline` mode;
- [ ] Write documentation for `diff` mode;
- [ ] Add missing information to dynamic rules documentation;
- [ ] Add CONTRIBUTION.md document.

Fixes #525
