### ISSUE TITLE
Enable (at least some) embedded dynamic rules by default

### ISSUE THREAD

**Issue by quasilyte** [VKCOM/noverify#467]
Issues that need to be resolved before that (this list can be extended over time):
- [x] #465 implement and use `@pure` attr where needed
- [x] measure the performance impact, optimize if necessary (old results can be outdated)
- [ ] add function-based grouping syntax (a separate issue needs to be created)

Optional:
- [x] #466 make dynamic rules more discoverable (as all other checks)
- [x] #323 implement report message variable interpolation

**Comment by quasilyte** [comment]
#469 helps to analyze the matching complexity of various patterns.

Any pathological cases can be tested there. Tests (hopefully) would keep us from hitting regression afterwards.
